[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = {path="../chess"}
chess_engine = {path="../chess_engine"}
sdl2 = {version="0.36.0"}